### api-1

GET http://localhost:3000/players/

### api-2

POST http://localhost:3000/players/
Content-Type: application/json

{
  "playerName": "Vishal",
  "jerseyNumber": 17,
  "role": "Bowler"
}

### api-3
GET http://localhost:3000/players/1/



### api-4

PUT http://localhost:3000/players/15/
Content-Type: application/json

{
  "playerName": "Maneesh",
  "jerseyNumber": 54,
  "role": "All-rounder"
}



### api-5

DELETE http://localhost:3000/players/13/
